"""
tickers.py
Provides a static list of prominent Indian Stock Market tickers.
Includes major Nifty 50 and large-cap components.
"""

INDIAN_STOCKS = [
    {"symbol": "RELIANCE.NS", "name": "Reliance Industries"},
    {"symbol": "TCS.NS", "name": "Tata Consultancy Services"},
    {"symbol": "HDFCBANK.NS", "name": "HDFC Bank"},
    {"symbol": "ICICIBANK.NS", "name": "ICICI Bank"},
    {"symbol": "BHARTIARTL.NS", "name": "Bharti Airtel"},
    {"symbol": "SBIN.NS", "name": "State Bank of India"},
    {"symbol": "INFY.NS", "name": "Infosys"},
    {"symbol": "LICI.NS", "name": "Life Insurance Corporation"},
    {"symbol": "ITC.NS", "name": "ITC"},
    {"symbol": "HINDUNILVR.NS", "name": "H हिंदुस्तान Unilever"},
    {"symbol": "LT.NS", "name": "Larsen & Toubro"},
    {"symbol": "BAJFINANCE.NS", "name": "Bajaj Finance"},
    {"symbol": "HCLTECH.NS", "name": "HCL Technologies"},
    {"symbol": "MARUTI.NS", "name": "Maruti Suzuki"},
    {"symbol": "SUNPHARMA.NS", "name": "Sun Pharmaceutical"},
    {"symbol": "TATAMOTORS.NS", "name": "Tata Motors"},
    {"symbol": "KOTAKBANK.NS", "name": "Kotak Mahindra Bank"},
    {"symbol": "ONGC.NS", "name": "Oil and Natural Gas Corp"},
    {"symbol": "AXISBANK.NS", "name": "Axis Bank"},
    {"symbol": "NTPC.NS", "name": "NTPC"},
    {"symbol": "TATASTEEL.NS", "name": "Tata Steel"},
    {"symbol": "POWERGRID.NS", "name": "Power Grid Corp"},
    {"symbol": "ASIANPAINT.NS", "name": "Asian Paints"},
    {"symbol": "WIPRO.NS", "name": "Wipro"},
    {"symbol": "COALINDIA.NS", "name": "Coal India"},
    {"symbol": "BAJAJFINSV.NS", "name": "Bajaj Finserv"},
    {"symbol": "NESTLEIND.NS", "name": "Nestle India"},
    {"symbol": "TITAN.NS", "name": "Titan Company"},
    {"symbol": "M&M.NS", "name": "Mahindra & Mahindra"},
    {"symbol": "ULTRACEMCO.NS", "name": "UltraTech Cement"},
    {"symbol": "TECHM.NS", "name": "Tech Mahindra"},
    {"symbol": "HINDALCO.NS", "name": "Hindalco Industries"},
    {"symbol": "GRASIM.NS", "name": "Grasim Industries"},
    {"symbol": "JSWSTEEL.NS", "name": "JSW Steel"},
    {"symbol": "INDUSINDBK.NS", "name": "IndusInd Bank"},
    {"symbol": "DRREDDY.NS", "name": "Dr. Reddy's Labs"},
    {"symbol": "CIPLA.NS", "name": "Cipla"},
    {"symbol": "BAJAJ-AUTO.NS", "name": "Bajaj Auto"},
    {"symbol": "EICHERMOT.NS", "name": "Eicher Motors"},
    {"symbol": "DIVISLAB.NS", "name": "Divi's Laboratories"},
    {"symbol": "HDFCLIFE.NS", "name": "HDFC Life Insurance"},
    {"symbol": "SBILIFE.NS", "name": "SBI Life Insurance"},
    {"symbol": "BRITANNIA.NS", "name": "Britannia Industries"},
    {"symbol": "BPCL.NS", "name": "Bharat Petroleum Corp"},
    {"symbol": "APOLLOHOSP.NS", "name": "Apollo Hospitals"},
    {"symbol": "HEROMOTOCO.NS", "name": "Hero MotoCorp"},
    {"symbol": "SHREECEM.NS", "name": "Shree Cement"},
    {"symbol": "TATACONSUM.NS", "name": "Tata Consumer Products"},
]
